[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sbmltoodejax"
version = "0.4.3"
dependencies = [
    "jax",
    "equinox",
    "sbmltoodepy",
]

[tool.setuptools.packages.find]
include = ["sbmltoodejax*"]

